import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import HowItWorksCopilot from '@/components/HowItWorksCopilot';

import productDocumentationContent from '/docs/PRODUCT_DOCUMENTATION.md?raw';
import technicalDocumentationContent from '/docs/TECHNICAL_DOCUMENTATION.md?raw';
import { useAuth } from '@/integrations/supabase/auth'; // Import useAuth

const content = `
## How to Download PDF Reports

SentiVibe allows you to easily download your analysis and comparison reports as professional PDF documents.

### Key Features:
*   **One-Click Download:** Generate a PDF with a single click from any analysis or comparison report page.
*   **Comprehensive Content:** The PDF includes all the details from your report, including AI insights, custom Q&A, and top comments.
*   **Branded Header:** Each PDF features a SentiVibe branded header for a professional look.
*   **Watermarking:** Free Tier users will have their PDF reports watermarked with "SentiVibe - Free Tier." Paid Tier users receive unwatermarked reports.
*   **Shareable & Archivable:** Perfect for sharing insights with colleagues, clients, or for archiving your research.

### Steps:
1.  **View a Report:** Navigate to any single video analysis report or multi-video comparison report.
2.  **Click "Download Report PDF":** Locate and click the "Download Report PDF" button, usually found near the top of the report.
3.  **Save the File:** Your browser will prompt you to save the generated PDF file to your device. The filename will be automatically generated based on the report's title.

This feature ensures you can easily share and retain the valuable insights generated by SentiVibe.
`;

const PdfExportGuide = () => {
  useEffect(() => {
    document.title = "Download PDF Reports - SentiVibe Guide";
  }, []);

  const { subscriptionStatus, subscriptionPlanId } = useAuth();
  const isPaidTier = subscriptionStatus === 'active' && subscriptionPlanId !== 'free';

  return (
    <div className="container mx-auto p-4 max-w-5xl flex flex-col md:flex-row gap-6 bg-background text-foreground">
      {/* HowItWorksSidebar is rendered by the parent HowItWorks.tsx */}
      <Card className="flex-1 mb-6 bg-card border-border">
        <CardHeader>
          <CardTitle className="text-3xl font-bold text-center">Download PDF Reports</CardTitle>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {content}
          </ReactMarkdown>
          <div className="mt-8 flex justify-center">
            <HowItWorksCopilot
              productDocumentation={productDocumentationContent}
              technicalDocumentation={technicalDocumentationContent}
              isPaidTier={isPaidTier} // Pass isPaidTier to HowItWorksCopilot
            />
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default PdfExportGuide;