import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
// Removed 'Link' import as it's only used in Markdown, not as a React component.

const PdfExportGuide = () => {
  useEffect(() => {
    document.title = "Download PDF Reports - SentiVibe Guide";
  }, []);

  const content = `
# How to Download PDF Reports: Professional, Shareable Insights

SentiVibe provides the capability to export your detailed video analysis and multi-comparison reports as professional, high-quality PDF documents. This guide explains exactly how to do it, what comprehensive content is included, and the distinction between Free and Paid Tier reports.

## 1. Where to Download Reports

The "Download Report PDF" button is strategically placed on all pages where a full analysis or comparison report is displayed:

*   **Single Video Analysis Report Page:** After performing an analysis on the \`/analyze-video\` page.
*   **Single Video Blog Post Detail Page:** On the \`/blog/:slug\` page for any individual video analysis.
*   **Multi-Video Comparison Report Page:** After performing a comparison on the \`/create-multi-comparison\` page.
*   **Multi-Video Comparison Blog Post Detail Page:** On the \`/multi-comparison/:slug\` page for any multi-video comparison.

Look for the prominent **(Download icon) "Download Report PDF"** button to initiate the export.

## 2. Comprehensive Content of the PDF Report

The generated PDF report is a meticulously structured and comprehensive document, designed to capture every detail of your analysis or comparison for easy sharing and archiving. It includes:

*   **Branded Header:** A professional header featuring the SentiVibe logo and the clear tagline "YouTube Audience Insight Report." This ensures brand consistency and immediate recognition.
*   **Video/Comparison Details:** All essential information about the video(s) or comparison is included:
    *   Titles, descriptions, and creator names.
    *   Video thumbnails for visual context.
    *   Relevant timestamps such as "Published on," "Last updated," and "Last Full Analysis/Comparison."
    *   Original YouTube video links.
*   **AI-Generated Insights:** The core of your report, presenting the AI's findings:
    *   **For Single Videos:** Overall sentiment, emotional tones, key themes, and the detailed summary insights.
    *   **For Multi-Videos:** Structured comparative data including overall sentiment trends, common/divergent emotional tones, common/unique themes, summary insights, and individual video summaries.
*   **Community Q&A Section:** All AI-generated answers to custom questions (for single videos) or custom comparative questions (for multi-videos) are fully integrated into the report. This includes both your questions and any questions previously asked by the community, providing a complete knowledge base.
*   **Top Raw Comments:** For transparency and direct reference, the top 10 most popular comments (by like count) are listed:
    *   For single video reports, the top 10 comments from that video.
    *   For multi-video reports, the top 10 comments for *each* individual video included in the comparison.
*   **Full Blog Post Content:** The complete SEO-optimized blog post content, generated by AI, is also included. This provides a narrative summary of the analysis or comparison, suitable for content distribution.
*   **Branded Footer:** A footer with copyright information and a clear disclaimer that "Analyses generated by AI based on public YouTube comments."

## 3. Free Tier vs. Paid Tier PDF Reports: The Watermark Distinction

SentiVibe offers a clear distinction in PDF report quality based on your subscription tier:

*   **Free Tier Reports:** If you are currently using the Free Tier (applicable to both unauthenticated users and authenticated users without an active paid subscription), your generated PDF reports will include a **"SentiVibe - Free Tier" watermark**. This watermark is subtly placed across the report pages, indicating the tier of service used for generation.
*   **Paid Tier Reports:** Users with an active Paid Tier subscription receive **unwatermarked, professional PDF reports**. This premium benefit ensures your reports are clean, polished, and ready for any professional presentation without branding overlays.

## 4. Optimal Usage Tips for PDF Export

*   **Verify Content Before Download:** Always ensure that the full report content, including all AI insights and custom Q&A, is completely loaded and visible on the page before clicking the "Download Report PDF" button. This guarantees that all data is accurately captured in the PDF.
*   **Automatic Filename:** The PDF filename is automatically generated based on the video or comparison title (e.g., \`SentiVibe_Report_VideoTitle.pdf\`) for easy organization and retrieval.
*   **Share & Archive:** These comprehensive PDF reports are ideal for:
    *   **Sharing Insights:** Distribute findings with clients, team members, or stakeholders who may not have direct access to the SentiVibe platform.
    *   **Archiving Research:** Maintain a professional record of your video analyses and comparative studies for future reference or compliance.
    *   **Presentations:** Use the clean, structured reports as handouts or visual aids in presentations.
*   **Upgrade for Professionalism:** If unwatermarked reports are crucial for your professional needs, consider upgrading to a Paid Tier for a seamless, premium experience.

By following these guidelines, you can effectively generate and utilize SentiVibe's professional PDF reports to disseminate your audience insights with clarity and impact.
  `;

  return (
    <div className="container mx-auto p-4 max-w-3xl">
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="text-3xl font-bold text-center">Download PDF Reports</CardTitle>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {content}
          </ReactMarkdown>
        </CardContent>
      </Card>
    </div>
  );
};

export default PdfExportGuide;