import { Link } from 'react-router-dom';

const Footer = () => {
  return (
    <footer className="bg-background text-muted-foreground py-4 text-center border-t border-border">
      <div className="container mx-auto px-4">
        <p className="text-sm mb-1">&copy; {new Date().getFullYear()} SentiVibe. All rights reserved.</p>
        <p className="text-xs text-muted-foreground mb-2">SentiVibe: Your Audience, Understood. Analyses generated by AI based on public YouTube comments.</p>
        <div className="flex justify-center space-x-4 text-sm">
          <Link to="/terms-of-service" className="hover:underline text-accent">Terms of Service</Link>
          <Link to="/privacy-notice" className="hover:underline text-accent">Privacy Notice</Link>
          <Link to="/refund-policy" className="hover:underline text-accent">Refund Policy</Link>
        </div>
      </div>
    </footer>
  );
};

export default Footer;