import React from 'react';

const Footer = () => {
  return (
    <footer className="bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400 py-4 text-center border-t border-gray-200 dark:border-gray-800">
      <div className="container mx-auto px-4">
        <p className="text-sm mb-1">&copy; {new Date().getFullYear()} SentiVibe. All rights reserved.</p>
        <p className="text-xs text-gray-500 dark:text-gray-500">Analyses generated by AI based on public YouTube comments.</p>
      </div>
    </footer>
  );
};

export default Footer;