import { Link } from 'react-router-dom';

const Footer = () => {
  return (
    <footer className="bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400 py-4 text-center border-t border-gray-200 dark:border-gray-800">
      <div className="container mx-auto px-4">
        <p className="text-sm mb-1">&copy; {new Date().getFullYear()} SentiVibe. All rights reserved.</p>
        <p className="text-xs text-gray-500 dark:text-gray-500 mb-2">Analyses generated by AI based on public YouTube comments.</p>
        <div className="flex justify-center space-x-4 text-sm">
          <Link to="/terms-of-service" className="hover:underline">Terms of Service</Link>
          <Link to="/privacy-notice" className="hover:underline">Privacy Notice</Link>
          <Link to="/refund-policy" className="hover:underline">Refund Policy</Link>
        </div>
      </div>
    </footer>
  );
};

export default Footer;